### ISSUE TITLE
check dependabot alerts

### ISSUE THREAD

**Issue by 532910** [nspcc-dev/neofs-http-gw#100]
![image](https://user-images.githubusercontent.com/14617699/139798464-061d0754-d02f-4a0f-a94f-be09301066db.png)

https://github.com/nspcc-dev/neofs-http-gw/security/dependabot/go.sum/github.com%2Fopencontainers%2Frunc/open

**Comment by alexvanin** [comment]
As soon as https://github.com/testcontainers/testcontainers-go roll new version, we will update it. HTTP Gateway does not use runc library directly.

**Comment by realloc** [comment]
There is a fix, but not release yet.

**Comment by KirillovDenis** [comment]
Should we wait for release? Or we can just use [latest revision](https://github.com/testcontainers/testcontainers-go/commit/4b5710b46477e577e80f9201cd9572ab934c8ce9)?

**Comment by alexvanin** [comment]
> Should we wait for release? Or we can just use [latest revision](https://github.com/testcontainers/testcontainers-go/commit/4b5710b46477e577e80f9201cd9572ab934c8ce9)?

I would wait for the release, but also don't see any issues with update to a master branch.

**Comment by 532910** [comment]
The alert is still shown.

**Comment by alexvanin** [comment]
Now dependabot triggered again on `github.com/opencontainers/runc`. Seems that it is going to be never ending stream of alerts while we use testcontainer library for integration tests. 

The only thing we can do is to update testcontainer library on every release and ignore those alerts in the meantime. Therefore I close this issue, because there is no one time solution for that, except dropping testcontainer dependency.
