### ISSUE TITLE
Upgrade `fasthttp` module

### ISSUE THREAD

**Issue by cthulhu-rider** [nspcc-dev/neofs-http-gw#129]
For now the latest version of fasthttp is [v1.33.0](https://github.com/valyala/fasthttp/releases/tag/v1.33.0). I think I'd be useful to upgrade the used module.

I briefly ran through the changes that may affect the application:
* https://github.com/valyala/fasthttp/commit/6b558111301e8e280c12d1af939661940cad84ff Add MaxIdleWorkerDuration to Server. (https://github.com/valyala/fasthttp/pull/1183) (Kilos Liu)\
* https://github.com/valyala/fasthttp/commit/258a4c17b4f451f9a1f9bae3f34d3f5d6e9e0bfd fix: reset response after reset user values on keep-alive connections (https://github.com/valyala/fasthttp/pull/1176) (Sergio VS)
* https://github.com/valyala/fasthttp/commit/7db0597e75bf62e2731a30307c7cf338455a3f93 Fix bad request trailer panic (Erik Dubbelboer)
* https://github.com/valyala/fasthttp/commit/4aadf9a85e1fd9d653e8f5c05d3825f8369fd63e Fix parseTrailer panic (Erik Dubbelboer)
* https://github.com/valyala/fasthttp/commit/da7ff7a2080953e370e8bd712f5ae8ef8b0cb4e1 Add trailer support (https://github.com/valyala/fasthttp/pull/1165) (ichx)
* https://github.com/valyala/fasthttp/commit/017f0aa09d7fd802bd1760836e329734ea642180 fix: reset request after reset user values on keep-alive connections (https://github.com/valyala/fasthttp/pull/1162) (Sergio VS)
* https://github.com/valyala/fasthttp/commit/2ca01c7efb6dcd2d75b36571c857847b9a1b2592 fix: Status Line parsing and writing (https://github.com/valyala/fasthttp/pull/1135) (Shivansh Vij)
* https://github.com/valyala/fasthttp/commit/528dd6223902bf7b933dc03bcd2a848b54f77c00 feat: ability to read body separate from header (https://github.com/valyala/fasthttp/pull/1130) (Shivansh Vij)
* https://github.com/valyala/fasthttp/commit/556aa814e4d862f33c875cf9f0ebdf2867005092 feat: ability to edit status messages (https://github.com/valyala/fasthttp/pull/1126) (Valentin Paz Marcolla)
* https://github.com/valyala/fasthttp/commit/4cfec1a79583aaa94bf0ba132f448d4274c50a7e feat: make public Server.TLSConfig 
(https://github.com/valyala/fasthttp/pull/1128) (Sergio VS)
* https://github.com/valyala/fasthttp/commit/7fdd5261e8cc744f04c0a90d7319688179cf78e9 feat: a new userData API Remove (https://github.com/valyala/fasthttp/pull/1117) (tyltr)
* https://github.com/valyala/fasthttp/commit/713da4e33f2b5af08241edc5712cf43d7e3b0e65 Adding new compressible prefixes (https://github.com/valyala/fasthttp/pull/1092) (Kyle Unverferth)
* https://github.com/valyala/fasthttp/commit/63211032d43a89cc61ccc0d86174dbbe0cc1899b Various deadline fixes (https://github.com/valyala/fasthttp/pull/1081) (Erik Dubbelboer)
*

**Comment by KirillovDenis** [comment]
At least we should upgrade to [v1.34.0](https://github.com/valyala/fasthttp/releases/tag/v1.34.0) because there was [a fix](https://github.com/valyala/fasthttp/pull/1234) without which tests sometimes fail. Beside this using `v1.34.0` encountered with strange bug:
```
panic: context: internal error: missing cancel error

goroutine 22075 [running]:
context.(*cancelCtx).cancel(0xc000be4820, 0x90, {0x0, 0x0})
        /usr/local/go/src/context/context.go:399 +0x27e
context.propagateCancel.func1()
        /usr/local/go/src/context/context.go:281 +0xe2
created by context.propagateCancel
        /usr/local/go/src/context/context.go:278 +0x1d0
```

I'm not sure if the reason `v1.34.0` or problem in `neofs-http-gw` code

**Comment by alexvanin** [comment]
Don't think it is related, but I had some context cancel propagation errors in integration test with `-race` flag.

**Comment by KirillovDenis** [comment]
It seems the problem is using [`fasthttp.RequestCtx`](https://github.com/valyala/fasthttp/blob/master/server.go#L564) (in different gorountine ) after handler return. For example new routine created [here](https://github.com/nspcc-dev/neofs-api-go/blob/master/rpc/grpc/init.go#L77) when we try to upload object to NeoFS.

As a solution fasthttp suggests use `ctx.TimeoutError` before returns from handler, but this fails whole request.

Perhaps we can ignore this problem as it only occurs during the `server.Shutdown()` step.
