### ISSUE TITLE
Check usage of `time.Time`

### ISSUE THREAD

**Issue by alexvanin** [nspcc-dev/neofs-http-gw#214]
Gateway should live in the environment without NTP and pretty much unstable time flow. 

In this issue collect all available places where things can go wrong with wall time and discuss it with @realloc and @alexvanin

**Comment by KirillovDenis** [comment]
Currently, we use time.Time in the following cases:

1. To measure elapsed time of requests
2. To set object attribute `Timestamp` and convert it to `Last-Modified` header
3. To set `modified` time to files in zip archive
4. To compute object attribute `__NEOFS__EXPIRATION_EPOCH`

It seems the problem is only the last case (expiration attribute). We support the following headers:
* `X-Attribute-Neofs-Expiration-Epoch: 100`
* `X-Attribute-Neofs-Expiration-Duration: 24h30m`
* `X-Attribute-Neofs-Expiration-Timestamp: 1637574797`
* `X-Attribute-Neofs-Expiration-RFC3339: 2021-11-22T09:55:49Z`

Probably we can keep only `Expiration-Epoch` and `Expiration-Duration`.

**Comment by alexvanin** [comment]
1. Check monotonic timer 
2. Nothing we can do
3. Nothing we can do
4. Can we check request sender local time? We can get diff between current end expiration time and use to set duration.

**Comment by KirillovDenis** [comment]
1. We already use it (`time.Since()`).
4. It seems we can use the `Date` [header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Date).
